
### 회원가입
POST http://localhost:8001/api/signup
Content-Type: application/json

{  
    "userId": "tester1",  
    "nickname": "Tester1",  
    "password": "12345",  
    "confirm": "12345"
}

### 로그인
POST http://localhost:8001/api/login
Content-Type: application/json

{  
    "userId": "tester1",  
    "password": "12345"
}

### 설문결과 데이터 저장하면서 로그인
POST http://localhost:8001/api/login/withsave
Content-Type: application/json

{  
    "resultId": 1,  
    "userId": "tester1",  
    "password": "12345"
}