
#############------ Auth 관련 API ----------------

### 회원가입
POST http://localhost:8001/api/signup
Content-Type: application/json

{  
    "userId": "tester1",  
    "nickname": "Tester1",  
    "password": "12345",  
    "confirm": "12345"
}

### 로그인
POST http://localhost:8001/api/login
Content-Type: application/json

{  
    "userId": "tester1",  
    "password": "12345"
}

### 로그인
POST http://nodeapi.myspaceti.me:8002/api/login
Content-Type: application/json

{  
    "userId": "tester2",  
    "password": "12345"
}

### 설문결과 데이터 저장하면서 로그인
POST http://localhost:8001/api/login/withsave
Content-Type: application/json

{  
    "resultId": 1,  
    "userId": "tester1",  
    "password": "12345"
}

#############------ results 관련 API ----------------

### 설문 후 제출하고, 설문결과 저장 - 저장된 DB 번호를 리턴받음 
POST http://localhost:8001/api/results/submit
Content-Type: application/json

{ 
  "answersArr" :   
  ["자연", "고가", "아시아", "쇼핑", "휴양"]
}


### 저장된 DB 번호 가지고 - 전체 데이터 GET
GET http://localhost:8001/api/results/3
Content-Type: application/json

### 저장된 DB 번호 가지고 - 전체 데이터 GET
GET http://nodeapi.myspaceti.me:8002/api/results/3
Content-Type: application/json



#############------ mypage 관련 API ----------------


### 마이페이지에 넣을 나의 정보(아직은 userId, nickname 정도를 받아 응답하는 기능
GET http://localhost:8001/api/mypage
Content-Type: application/json

### 마이페이지에 넣을 나의 저장된 결과지 result 받아서 반환
GET http://localhost:8001/api/mypage/myanswers
Content-Type: application/json





#############--------- Temporary countryInfo Uploader -------------

### countryInfo 저장하는 임시 링크 
POST http://localhost:8001/api/temporary/createCountryInfo
Content-Type: application/json

{
    "countryCode": 250,
    "countryName": "프랑스",
    "countryDomain": "FR",
    "canVisit": "No",
    "visitInfo": "격리면제",
    "continent": "유럽",
    "capitalCity": "파리",
    "resultText": "문화가 살아 숨쉬는",
    "recommendedId": 18,
    "resultImageUrl": "https://i.natgeofe.com/k/04665f4a-3f8d-4b62-8ca3-09ce7dfc5a20/france-eiffel-tower_4x3.jpg",
    "officialWebpage": "",
    "getMoreDetail": "https://restcountries.com/v3.1/alpha/250"
  }